/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Rizka Hikmatul
 */
public class UICoffeeMenu extends javax.swing.JFrame {

    /**
     * Creates new form UICoffeeMenu
     */
    public UICoffeeMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        radCap = new javax.swing.JRadioButton();
        radLuwak = new javax.swing.JRadioButton();
        radAmerica = new javax.swing.JRadioButton();
        radTeh = new javax.swing.JRadioButton();
        radKopSu = new javax.swing.JRadioButton();
        chkNasi = new javax.swing.JCheckBox();
        chkMar = new javax.swing.JCheckBox();
        chkTelor = new javax.swing.JCheckBox();
        chkMie = new javax.swing.JCheckBox();
        chkRoti = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTax = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPay = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtSub = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnClr = new javax.swing.JButton();
        btnExt = new javax.swing.JButton();
        btnHit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        radCap.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        radCap.setForeground(new java.awt.Color(255, 255, 255));
        radCap.setText("Cappucino           9k");
        radCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radCapActionPerformed(evt);
            }
        });
        getContentPane().add(radCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 160, -1));

        radLuwak.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        radLuwak.setForeground(new java.awt.Color(255, 255, 255));
        radLuwak.setText("Kopi Luwak        11k");
        radLuwak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radLuwakActionPerformed(evt);
            }
        });
        getContentPane().add(radLuwak, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 160, -1));

        radAmerica.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        radAmerica.setForeground(new java.awt.Color(255, 255, 255));
        radAmerica.setText("Kopi Americano  5k");
        radAmerica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radAmericaActionPerformed(evt);
            }
        });
        getContentPane().add(radAmerica, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        radTeh.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        radTeh.setForeground(new java.awt.Color(255, 255, 255));
        radTeh.setText("Teh                      3k");
        radTeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radTehActionPerformed(evt);
            }
        });
        getContentPane().add(radTeh, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        radKopSu.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        radKopSu.setForeground(new java.awt.Color(255, 255, 255));
        radKopSu.setText("Kopi Susu            4k");
        radKopSu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radKopSuActionPerformed(evt);
            }
        });
        getContentPane().add(radKopSu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 150, -1));

        chkNasi.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        chkNasi.setForeground(new java.awt.Color(255, 255, 255));
        chkNasi.setText("Nasi Goreng    8k");
        getContentPane().add(chkNasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));

        chkMar.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        chkMar.setForeground(new java.awt.Color(255, 255, 255));
        chkMar.setText("Martabak       10k");
        getContentPane().add(chkMar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        chkTelor.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        chkTelor.setForeground(new java.awt.Color(255, 255, 255));
        chkTelor.setText("Telor Gulung   5k");
        chkTelor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTelorActionPerformed(evt);
            }
        });
        getContentPane().add(chkTelor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        chkMie.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        chkMie.setForeground(new java.awt.Color(255, 255, 255));
        chkMie.setText("Mie Ayam       9k");
        getContentPane().add(chkMie, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        chkRoti.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        chkRoti.setForeground(new java.awt.Color(255, 255, 255));
        chkRoti.setText("Roti Bakar       3k ");
        getContentPane().add(chkRoti, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        jScrollPane1.setViewportView(txtTax);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 90, -1));

        jScrollPane2.setViewportView(txtPay);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 90, -1));

        jScrollPane3.setViewportView(txtSub);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 90, -1));

        jLabel2.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pajak");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 80, 20));

        jLabel4.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Bayar");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 80, 20));

        jLabel5.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SubTotal");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 80, 20));

        btnClr.setBackground(new java.awt.Color(102, 102, 102));
        btnClr.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        btnClr.setForeground(new java.awt.Color(255, 255, 255));
        btnClr.setText("Clear");
        btnClr.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnClr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClrActionPerformed(evt);
            }
        });
        getContentPane().add(btnClr, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 130, -1));

        btnExt.setBackground(new java.awt.Color(102, 102, 102));
        btnExt.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        btnExt.setForeground(new java.awt.Color(255, 255, 255));
        btnExt.setText("Exit");
        btnExt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnExt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExtActionPerformed(evt);
            }
        });
        getContentPane().add(btnExt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 130, -1));

        btnHit.setBackground(new java.awt.Color(102, 102, 102));
        btnHit.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        btnHit.setForeground(new java.awt.Color(255, 255, 255));
        btnHit.setText("Hitung");
        btnHit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitActionPerformed(evt);
            }
        });
        getContentPane().add(btnHit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 130, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Dark Black Rustic Chalkboard Texture Cafe Menu.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radCapActionPerformed
        // ketika memilih kopi
            if(radCap.isSelected())
            radAmerica.setSelected(false);
             radKopSu.setSelected(false);
            radLuwak.setSelected(false);
            radTeh.setSelected(false);                 
    }//GEN-LAST:event_radCapActionPerformed

    private void radLuwakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radLuwakActionPerformed
        // ketika memilih kopi
            if(radLuwak.isSelected())
            radAmerica.setSelected(false);
             radKopSu.setSelected(false);
            radAmerica.setSelected(false);
            radTeh.setSelected(false);
    }//GEN-LAST:event_radLuwakActionPerformed

    private void radAmericaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radAmericaActionPerformed
        if(radAmerica.isSelected())
            radCap.setSelected(false);
             radKopSu.setSelected(false);
            radLuwak.setSelected(false);
            radTeh.setSelected(false);
    }//GEN-LAST:event_radAmericaActionPerformed

    private void radTehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radTehActionPerformed
        // ketika memilih kopi
            if(radTeh.isSelected())
            radAmerica.setSelected(false);
             radKopSu.setSelected(false);
            radLuwak.setSelected(false);
            radCap.setSelected(false);
    }//GEN-LAST:event_radTehActionPerformed

    private void radKopSuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radKopSuActionPerformed
        // ketika memilih kopi
            if(radKopSu.isSelected())
            radAmerica.setSelected(false);
             radCap.setSelected(false);
            radLuwak.setSelected(false);
            radTeh.setSelected(false);
    }//GEN-LAST:event_radKopSuActionPerformed

    private void chkTelorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTelorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkTelorActionPerformed

    private void btnClrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClrActionPerformed
        // TODO add your handling code here:
        radAmerica.setSelected(false);
        radCap.setSelected(false);
        radKopSu.setSelected(false);
        radLuwak.setSelected(false);
        radTeh.setSelected(false);
        chkMar.setSelected(false);
        chkMie.setSelected(false);
        chkNasi.setSelected(false);
        chkTelor.setSelected(false);
        chkRoti.setSelected(false);
        txtPay.setText("");
        txtSub.setText("");
        txtTax.setText("");
                
    }//GEN-LAST:event_btnClrActionPerformed

    private void btnExtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExtActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExtActionPerformed

    private void btnHitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitActionPerformed
        int subTotal = 0;
        int total;
        final int TAX = 500;
        int tax;
        
        if(radAmerica.isSelected()) {
            subTotal = subTotal + 5000;
        } else if(radCap.isSelected()) {
            subTotal = subTotal + 9000;
        } else if(radKopSu.isSelected()) {
            subTotal = subTotal + 4000;
        } else if(radLuwak.isSelected()) {
            subTotal = subTotal + 11000;
        } else if(radTeh.isSelected()) {
            subTotal = subTotal + 3000;
        }
        
        if(chkRoti.isSelected()) {
            subTotal = subTotal + 3000;
        } if(chkTelor.isSelected()){
            subTotal = subTotal + 5000;
        } if(chkMie.isSelected()) {
            subTotal = subTotal + 9000;
        } if(chkMar.isSelected()) {
            subTotal = subTotal + 11000;
        } if(chkNasi.isSelected()) {
            subTotal = subTotal + 8000;
        }
//        char satuan = 'k';
        txtSub.setText(Integer.toString(subTotal));
        subTotal = Integer.parseInt(txtSub.getText());
        tax = TAX;
        total = subTotal + tax;
        
        
        txtTax.setText(Integer.toString(tax));
        txtPay.setText(Integer.toString(total));
    }//GEN-LAST:event_btnHitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UICoffeeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UICoffeeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UICoffeeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UICoffeeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UICoffeeMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClr;
    private javax.swing.JButton btnExt;
    private javax.swing.JButton btnHit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkMar;
    private javax.swing.JCheckBox chkMie;
    private javax.swing.JCheckBox chkNasi;
    private javax.swing.JCheckBox chkRoti;
    private javax.swing.JCheckBox chkTelor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton radAmerica;
    private javax.swing.JRadioButton radCap;
    private javax.swing.JRadioButton radKopSu;
    private javax.swing.JRadioButton radLuwak;
    private javax.swing.JRadioButton radTeh;
    private javax.swing.JTextPane txtPay;
    private javax.swing.JTextPane txtSub;
    private javax.swing.JTextPane txtTax;
    // End of variables declaration//GEN-END:variables
}
